### PR TITLE
Markdown corrected

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Grammatically correct
part of #6

### CODE REVIEW

**Review by Qamar30 — CHANGES_REQUESTED** [review]
I spell checked most the spelling not just  a.

**Comment by himanshu007-creator** [comment]
> I spell checked most the spelling not just a.

what?

**Review by himanshu007-creator — COMMENTED** [review]
what i need to do?

**Comment by Qamar30** [comment]
The headings should not be plurals documentations -> documentation  etc.  The whole readme file needs to be checked I already made some changes.  Look for duplicate headings etc. Just grammar

**Review by Qamar30 — CHANGES_REQUESTED** [review]
remove the explanations under the topics  i.e. the green highleted sections

**Review by Qamar30 — CHANGES_REQUESTED** [review]
There are still problems. it's fine ill fix the issue and close it

**Pull request closed without merging**
